FROM node:16-alpine
WORKDIR /var/run

RUN apk add git
RUN git clone https://github.com/hakimel/reveal.js.git
RUN cd reveal.js && npm install

WORKDIR /var/run/reveal.js

COPY index.html index.html
COPY slides/ slides/
EXPOSE 80
CMD npm start -- --host=0.0.0.0 --port=80