site_name: Container in der Praxis
dev_addr: "0.0.0.0:8080"
theme: "material"
site_author: "Jan Mahn (c't magazin)"
extra_css:
    - css/extra.css
markdown_extensions:
    - attr_list
    - admonition
    - fontawesome_markdown
plugins:
    - pdf-export:
          verbose: true
          media_type: print
          combined: true

nav:
    - Willkommen: index.md
    - Einrichtung: setup/index.md
    - Labs:
          - "Lab 1: Erste Schritte": lab1/index.md
          - "Lab 2: Arbeiten mit Images": lab2/index.md
          - "Lab 3: Komplexe Zusammenstellungen": lab3/index.md
          - "Lab 4: Automatisch bauen": lab4/index.md
          - "Lab 5: Nützliche Helfer": lab5/index.md
          - "Lab 6: HTTP-Routing": lab6/index.md
    - Docker unter Windows: windows/index.md
    - Ausblick und Fragen: outlook/index.md
    - Infos: about/index.md
