#build stage
FROM python:3 AS build
COPY ./mkdocs/ /mkdocs/
WORKDIR /mkdocs/
RUN pip install --upgrade pip && pip install mkdocs mkdocs-material
RUN mkdocs build

#web server stage
FROM nginx:alpine
COPY --from=0 /mkdocs/site/ /usr/share/nginx/html
EXPOSE 80
