name: Build presentation

on:
  push:
    branches: [master]
    paths:
      - presentation/**
      - .github/workflows/docker-presentation.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          dockerfile: presentation/Dockerfile-prod
          path: presentation
          username: jamct
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: jamct/workshop/presentation
          registry: ghcr.io
          tags: latest
