name: Build presentation

on:
  push:
    branches: [ master ]
    paths:
      - presentation/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ./presentation/Dockerfile-prod --tag docker.pkg.github.com/jamct/docker-training/presentation:latest
    - uses: docker/build-push-action@v1
      with:
        username: jamct
        password: ${{ secrets.GITHUB_TOKEN }}
        repository: jamct/docker-training/presentation:latest
        registry: docker.pkg.github.com
        tags: latest
